vimc-objs := vimc-core.o
vimc_common-objs := vimc-common.o
vimc_debayer-objs := vimc-debayer.o
vimc_scaler-objs := vimc-scaler.o
vimc_sensor-objs := vimc-sensor.o
vimc_vdev-objs := vimc-vdev.o

obj-$(CONFIG_VIDEO_VIMC) += vimc.o vimc_common.o vimc-debayer.o vimc_scaler.o \
				vimc_sensor.o vimc_vdev.o
